pipeline {
    agent any
    
    stages {
        stage('Install dependencies') {
            steps {
                dir('jenkins-python-pytest-demo') {
                    sh 'python3 -m venv venv'
                    sh './venv/bin/pip install -r requirements.txt'
                }
            }
        }
        
        stage('Run tests') {
            steps {
                dir('jenkins-python-pytest-demo') {
                    sh './venv/bin/pytest --junitxml=report.xml'
                }
            }
        }
        
        stage('Publish Report') {
            steps {
                dir('jenkins-python-pytest-demo') {
                    junit 'report.xml'
                }
            }
        }
    }
}
